name: lucky_8
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.16.0
  shared_preferences: ^2.2.2
  gradient_borders: ^1.0.0
  flutter_bloc: ^8.1.5
  flame_audio: ^2.10.0
  url_launcher: ^6.2.5
  share_plus: ^8.0.2
  rate_my_app: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: any

flutter_native_splash:
  background_image: assets/images/luc_splash_uuu.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/f/
    - assets/audio/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Black.ttf
          weight: 900
